#!/usr/bin/env python3
"""Run the offline preflight for the first pyRevit MVP sandbox session.

This command stays read-only. It does not launch Revit, install pyRevit, or
touch any Revit model. It wraps the existing offline checks into one repeatable
entrypoint so a human operator can confirm local readiness before the first
live sandbox run.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "docs" / "drafts" / "sandbox-preflight-report.md"
PYTHON = sys.executable


@dataclass
class Step:
    name: str
    args: list[str]
    expect_success: bool = True
    required_text: str = ""


@dataclass
class StepResult:
    step: Step
    returncode: int
    stdout: str
    passed: bool
    note: str


def build_steps() -> list[Step]:
    return [
        Step(
            name="Compile offline tools",
            args=[
                PYTHON,
                "tools\\check_offline_python_syntax.py",
            ],
            required_text="Summary: 0 errors",
        ),
        Step(
            name="Check pyRevit extension layout",
            args=[PYTHON, "tools\\check_pyrevit_extension.py"],
            required_text="Summary: 0 errors",
        ),
        Step(
            name="Run static checks and write report",
            args=[PYTHON, "tools\\static_checks.py", "--write-report"],
            required_text="Summary: 0 errors",
        ),
        Step(
            name="Validate valid room CSV fixture",
            args=[
                PYTHON,
                "tools\\validate_apply_csv.py",
                "--kind",
                "room",
                "--csv",
                "tests\\fixtures\\missing_room_numbers_valid.csv",
            ],
            required_text="INFO: YA-APPLY-ROOM-CSV-000",
        ),
        Step(
            name="Validate valid mark CSV fixture",
            args=[
                PYTHON,
                "tools\\validate_apply_csv.py",
                "--kind",
                "mark",
                "--csv",
                "tests\\fixtures\\missing_door_window_marks_valid.csv",
            ],
            required_text="INFO: YA-APPLY-MARK-CSV-000",
        ),
        Step(
            name="Validate duplicate room CSV fixture",
            args=[
                PYTHON,
                "tools\\validate_apply_csv.py",
                "--kind",
                "room",
                "--csv",
                "tests\\fixtures\\missing_room_numbers_duplicate.csv",
            ],
            expect_success=False,
            required_text="ERROR: YA-APPLY-ROOM-CSV-007",
        ),
        Step(
            name="Validate duplicate mark CSV fixture",
            args=[
                PYTHON,
                "tools\\validate_apply_csv.py",
                "--kind",
                "mark",
                "--csv",
                "tests\\fixtures\\missing_door_window_marks_duplicate.csv",
            ],
            expect_success=False,
            required_text="ERROR: YA-APPLY-MARK-CSV-007",
        ),
    ]


def run_step(step: Step) -> StepResult:
    completed = subprocess.run(
        step.args,
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    output = (completed.stdout or "") + (completed.stderr or "")
    success_matches = completed.returncode == 0
    expected_rc = success_matches if step.expect_success else not success_matches
    text_matches = not step.required_text or step.required_text in output
    passed = expected_rc and text_matches

    if not expected_rc:
        if step.expect_success:
            note = f"Expected exit code 0, got {completed.returncode}."
        else:
            note = f"Expected a failing exit code, got {completed.returncode}."
    elif not text_matches:
        note = f"Expected output to include: {step.required_text}"
    else:
        note = "OK"

    return StepResult(
        step=step,
        returncode=completed.returncode,
        stdout=output.strip(),
        passed=passed,
        note=note,
    )


def write_report(path: Path, results: list[StepResult]) -> None:
    failed = [result for result in results if not result.passed]
    lines = [
        "# YangAgent Sandbox Preflight Report",
        "",
        "Generated by `python tools/run_sandbox_preflight.py --write-report`.",
        "This preflight is read-only and does not launch Revit.",
        "",
        "## Summary",
        "",
        f"- Passed steps: {len(results) - len(failed)}/{len(results)}",
        f"- Failed steps: {len(failed)}",
        "",
        "## Step Results",
        "",
    ]
    for result in results:
        status = "PASS" if result.passed else "FAIL"
        lines.append(f"- `{status}` {result.step.name} - {result.note}")
    lines.extend(["", "## Command Output", ""])
    for result in results:
        lines.append(f"### {result.step.name}")
        lines.append("")
        lines.append(f"- Exit code: `{result.returncode}`")
        lines.append(f"- Expected success: `{result.step.expect_success}`")
        lines.append("")
        lines.append("```text")
        lines.append(result.stdout or "(no output)")
        lines.append("```")
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-report", action="store_true", help="Write a Markdown report.")
    parser.add_argument("--report", default=str(DEFAULT_REPORT), help="Override the report path.")
    args = parser.parse_args()

    results = [run_step(step) for step in build_steps()]
    for result in results:
        status = "PASS" if result.passed else "FAIL"
        print(f"{status}: {result.step.name}: {result.note}")

    if args.write_report:
        report_path = Path(args.report)
        write_report(report_path, results)
        print(f"Report: {report_path.relative_to(ROOT).as_posix()}")

    return 1 if any(not result.passed for result in results) else 0


if __name__ == "__main__":
    raise SystemExit(main())
